# Generated by Django 5.0.1 on 2024-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_tag_quote_content_quote_user_remove_quote_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
